---
- hosts: db
  become: yes
  gather_facts: 0
  tasks:
     - name: Install packages
       yum:
         name: "{{item}}"
         state: present
 #      with_items:
       loop:
         - curl
         - finger
         - wget
         - httpd
         - ntp


